(defvar yxl-datascience-additional-docs
  '(("R - quantreg" . "https://cran.r-project.org/web/packages/quantreg/quantreg.pdf")
    ("Moab" . "http://docs.adaptivecomputing.com/torque/6-1-1/adminGuide/help.htm#topics/moabWorkloadManager/topics/moabCommands/a.gcommandoverview.html")
    ("Slurm" . "https://slurm.schedmd.com/")
    ("Cpp - Armadillo" . "http://arma.sourceforge.net/docs.html")
    ("Python - strftime" . "http://strftime.org/")
    ("Python - string format" . "https://pyformat.info/")
    ("GFM" . "https://guides.github.com/features/mastering-markdown/")
    ("org-babel" . "http://orgmode.org/manual/Specific-header-arguments.html")
    ("R - adv-r" . "http://adv-r.had.co.nz/")
    ("R - rmarkdown - html" . "http://rmarkdown.rstudio.com/html_document_format.html")
    ("R - rmarkdown - cheatsheet" . "https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf")
    ("R - knitr - options" . "https://yihui.name/knitr/options/")
    ("R - bookdown" . "https://bookdown.org/yihui/bookdown/")
    ("R - blogdown" . "https://bookdown.org/yihui/blogdown/")
    ("R - igraph" . "http://igraph.org/r/doc/00Index.html")
    ("R - cowplot" . "https://cran.r-project.org/web/packages/cowplot/")
    ("R - modelr" . "https://cran.r-project.org/web/packages/modelr/modelr.pdf")
    ("R - GGally" . "http://ggobi.github.io/ggally/")
    ("R - tidyverse - dplyr" . "http://dplyr.tidyverse.org/reference/index.html")
    ("R - tidyverse - stringr" . "http://stringr.tidyverse.org/reference/index.html")
    ("R - tidyverse - purrr" . "http://purrr.tidyverse.org/reference/index.html")
    ("Color - solarized" . "http://ethanschoonover.com/solarized")
    ("Color - gruvbox" . "https://github.com/morhetz/gruvbox")
    ("Color - material" . "https://material.io/guidelines/style/color.html#color-color-palette")
    ("Color - hexrgb" . "https://www.webpagefx.com/web-design/hex-to-rgb/")))
